# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/quantum_switch.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/quantum_switch.proto\x12\x11quantum.switch.v1\"$\n\x13\x43rossConnectRequest\x12\r\n\x05state\x18\x01 \x01(\x08\"8\n\x14\x43rossConnectResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x0f\n\rStatusRequest\";\n\x0eStatusResponse\x12\x14\n\x0cis_connected\x18\x01 \x01(\x08\x12\x13\n\x0bswitch_type\x18\x02 \x01(\t2\xd8\x01\n\x14QuantumSwitchService\x12\x62\n\x0fSetCrossConnect\x12&.quantum.switch.v1.CrossConnectRequest\x1a\'.quantum.switch.v1.CrossConnectResponse\x12\\\n\x15GetCrossConnectStatus\x12 .quantum.switch.v1.StatusRequest\x1a!.quantum.switch.v1.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.quantum_switch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CROSSCONNECTREQUEST']._serialized_start=49
  _globals['_CROSSCONNECTREQUEST']._serialized_end=85
  _globals['_CROSSCONNECTRESPONSE']._serialized_start=87
  _globals['_CROSSCONNECTRESPONSE']._serialized_end=143
  _globals['_STATUSREQUEST']._serialized_start=145
  _globals['_STATUSREQUEST']._serialized_end=160
  _globals['_STATUSRESPONSE']._serialized_start=162
  _globals['_STATUSRESPONSE']._serialized_end=221
  _globals['_QUANTUMSWITCHSERVICE']._serialized_start=224
  _globals['_QUANTUMSWITCHSERVICE']._serialized_end=440
# @@protoc_insertion_point(module_scope)
