# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import quantum_switch_pb2 as proto_dot_quantum__switch__pb2


class QuantumSwitchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetCrossConnect = channel.unary_unary(
                '/quantum.switch.v1.QuantumSwitchService/SetCrossConnect',
                request_serializer=proto_dot_quantum__switch__pb2.CrossConnectRequest.SerializeToString,
                response_deserializer=proto_dot_quantum__switch__pb2.CrossConnectResponse.FromString,
                )
        self.GetCrossConnectStatus = channel.unary_unary(
                '/quantum.switch.v1.QuantumSwitchService/GetCrossConnectStatus',
                request_serializer=proto_dot_quantum__switch__pb2.StatusRequest.SerializeToString,
                response_deserializer=proto_dot_quantum__switch__pb2.StatusResponse.FromString,
                )


class QuantumSwitchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SetCrossConnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCrossConnectStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuantumSwitchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetCrossConnect': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCrossConnect,
                    request_deserializer=proto_dot_quantum__switch__pb2.CrossConnectRequest.FromString,
                    response_serializer=proto_dot_quantum__switch__pb2.CrossConnectResponse.SerializeToString,
            ),
            'GetCrossConnectStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCrossConnectStatus,
                    request_deserializer=proto_dot_quantum__switch__pb2.StatusRequest.FromString,
                    response_serializer=proto_dot_quantum__switch__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantum.switch.v1.QuantumSwitchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuantumSwitchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SetCrossConnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quantum.switch.v1.QuantumSwitchService/SetCrossConnect',
            proto_dot_quantum__switch__pb2.CrossConnectRequest.SerializeToString,
            proto_dot_quantum__switch__pb2.CrossConnectResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCrossConnectStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/quantum.switch.v1.QuantumSwitchService/GetCrossConnectStatus',
            proto_dot_quantum__switch__pb2.StatusRequest.SerializeToString,
            proto_dot_quantum__switch__pb2.StatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
